spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8000
  error:
    include-message: always

rsa:
  private-key: classpath:certs/private-keyy.pem
  public-key: classpath:certs/public-key.pem

logging:
  level:
    org:
      springframework: INFO